appender.abcd.type = File
appender.abcd.name = MyFile
appender.abcd.fileName = log/logfile.log
appender.abcd.layout.type = PatternLayout
appender.abcd.layout.pattern = %d %t [%c{1}] %level %msg %n
 
rootLogger.level = all
rootLogger.appenderRef.abcd.ref = MyFile